name: Test Manual Workflow with ChatGPT and Matrix

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Test Environnement'
        required: true
        default: '/dev'
      loglevel:
        description: 'Log Level'
        required: true
        default: 'info'

jobs:
  manual-job:
    runs-on: ubuntu-latest
    name: Test with Matrix
    strategy:
      matrix:
        environment: [DEV, PROD]  # Les deux environnements à tester

    environment: ${{ matrix.environment }}  # Dynamique en fonction de la matrice
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    
    steps:
      - name: Set MY_API_URL based on environment
        id: set_url
        run: |
          if [[ "${{ matrix.environment }}" == "DEV" ]]; then
            echo "MY_API_URL=https://dev.example.com" >> $GITHUB_ENV
          else
            echo "MY_API_URL=https://prod.example.com" >> $GITHUB_ENV
          fi

      - name: Application ${ { matrix.environment }}
        run: |
          echo "Mon application de test dans l'environnement ${{ matrix.environment }}"
          echo "Env Name: ${{ github.event.inputs.Environment }}"

      - name: GitHub Variable
        run: echo '${{ toJson(github) }}'

      - name: Runner Variable
        run: echo '${{ toJson(runner) }}'

      - name: Secrets Variable
        run: echo '${{ toJson(secrets) }}'

      - name: ChatGPT API Request
        run: |
          echo "Sending request to OpenAI API"
          response=$(curl -s https://api.openai.com/v1/completions \
            -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d '{
              "model": "gpt-3.5-turbo",
              "messages": [{"role": "user", "content": "Hello, ChatGPT from ${{ matrix.environment }}!"}],
              "max_tokens": 50
            }')
          echo "ChatGPT Response: $response"

      - name: Env Variable
        run: echo "MY_API_URL = ${{ env.MY_API_URL }}"
