name: Test Manual Workflow

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Test Environnement'
        required: true
        default: '/dev'
      loglevel:
        description: 'Log Level'
        required: true
        default: 'info'  # Default value for the loglevel

jobs:
  manual-job-DEV:
    runs-on: ubuntu-latest
    name: TEST-DEV
    if: ${{ github.ref == 'refs/heads/main' && github.event.inputs.loglevel == 'debug' }}  # Job condition
    environment: DEV

    steps:
      - name: Application DEV
        run: |
          echo "Mon application de test"
          echo "Env Name: ${{ github.event.inputs.Environment }}"

      - name: GitHub Variable
        run: echo '${{ toJson(github) }}'

      - name: Runner Variable
        run: echo '${{ toJson(runner) }}'

      - name: Secrets Variable
        run: echo '${{ toJson(secrets) }}'

      - name: Env Variable
        run: echo "MY_API_URL = ${{ env.MY_API_URL_DEV }}"

  manual-job-PROD:
    runs-on: ubuntu-latest
    name: TEST-PROD
    environment: PROD

    steps:
      - name: Application PROD
        run: |
          echo "Mon application de prod"
          echo "Env Name: ${{ github.event.inputs.Environment }}"

      - name: GitHub Variable
        run: echo '${{ toJson(github) }}'

      - name: Runner Variable
        run: echo '${{ toJson(runner) }}'

      - name: Secrets Variable
        run: echo '${{ toJson(secrets) }}'

      - name: Env Variable
        run: echo "MY_API_URL = ${{ env.MY_API_URL_PROD }}"
